# Generated by Django 6.1 on 2026-09-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='admin_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Ordered', 'Ordered'), ('Received', 'Received')], default='Pending', max_length=20),
        ),
    ]
