# Generated by Django 6.1 on 2026-08-25 20:48

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username_user_name_store_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.MyUserManager()),
            ],
        ),
    ]
